apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eks-webhook-proxy.fullname" . }}
  labels:
   {{- include "eks-webhook-proxy.labels" . | nindent 4 }}
data:
  PROXY_RESTRICTED: {{ .Values.options.webhookRestricted | quote }}
  PROXY_ALLOWED_CIDRS: {{ join "," .Values.options.webhookAllowedCIDRS | quote }}
