{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eks-webhook-proxy.fullname" . }}
  labels:
   {{- include "eks-webhook-proxy.labels" . | nindent 4 }}
{{- end }}
